version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: plat_adm_nginx
    volumes:
      - ./src:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8000:80
  golang:
    image: golang:latest
    container_name: plat_adm_golang
    volumes:
      - ./golang.sh:/go/golang.sh
      - ./src/:/go/admin-api/
      - ./vendor/go/pkg:/go/pkg
      - ./vendor/go/src:/go/src
    command: bash -c "/go/golang.sh"
    links:
      - database
    # command: bash -c "go get -u github.com/gin-gonic/gin && go run /go/src/app/router.go"
    ports:
      - 3000:4000
  database:
    image: postgres:11.2-alpine
    container_name: plat_adm_db
    restart: always
    environment:
      POSTGRES_PASSWORD: "asdasd"
    expose:
      - 5432
  adminer:
    image: adminer
    container_name: plat_adm_adminer
    restart: always
    ports:
      - 8080:8080
    links:
      - database
